# Generated by Django 5.2.5 on 2025-08-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
