# Generated by Django 5.2.5 on 2025-08-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='platform',
            field=models.CharField(default='amazon', max_length=100),
        ),
    ]
