# Generated by Django 5.2.5 on 2025-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_productlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
