# Generated by Django 5.2.5 on 2025-08-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_alter_productlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='is_audit_runnning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='is_audited_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
