# Generated by Django 5.2.5 on 2025-08-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_productlist_is_audit_runnning_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='is_audit_runnning',
            new_name='is_audit_running',
        ),
    ]
